#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=28gb
#PBS -l walltime=10:00:00

set -e
set -x

mkdir -p output
cp $(jq -r .bvecs config.json) output/dwi.bvecs
cp $(jq -r .bvals config.json) output/dwi.bvals
chmod -R +w output

dipy_denoise_lpca \
    --force \
    --out_dir output \
    --sigma $(jq -r .sigma config.json) \
    --patch_radius $(jq -r .patch_radius config.json) \
    --pca_method $(jq -r .pca_method config.json) \
    --tau_factor $(jq -r .tau_factor config.json) \
    --out_denoised dwi.nii.gz \
    $(jq -r .dwi config.json) $(jq -r .bvals config.json) $(jq -r .bvecs config.json)

echo "done"
